Class {
	#name : #FASTPharoModel,
	#superclass : #MooseModel,
	#category : #'FAST-Pharo-Model-Model'
}

{ #category : #accessing }
FASTPharoModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits' #'FAST-Core-Model')
]

{ #category : #meta }
FASTPharoModel class >> annotation [
	<FMClass: #FASTPharoModel super: #MooseModel>
	<package: #'FAST-Pharo-Model'>
	<generated>
]
