Class {
	#name : #FASTPharoUnknownSourceLanguage,
	#superclass : #FASTPharoSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'FAST-Pharo-Model-Entities'
}

{ #category : #meta }
FASTPharoUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FASTPharoSourceLanguage>
	<package: #'FAST-Pharo-Model'>
	<generated>
	^self
]
