Class {
	#name : #FASTPharoSourceLanguage,
	#superclass : #FASTEntity,
	#traits : 'FamixTSourceLanguage',
	#classTraits : 'FamixTSourceLanguage classTrait',
	#category : #'FAST-Pharo-Model-Entities'
}

{ #category : #meta }
FASTPharoSourceLanguage class >> annotation [

	<MSEClass: #SourceLanguage super: #FASTEntity>
	<package: #'FAST-Pharo-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTPharoSourceLanguage class >> generatedSlotNames [
	<generated>
	'FASTPharoSourceLanguage class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTPharoSourceLanguage class >> generatedTraitNames [
	<generated>
	^ #(FamixTSourceLanguage)
]

{ #category : #meta }
FASTPharoSourceLanguage class >> requirements [

	<generated>
	^ {  }
]
