Class {
	#name : #FASTPharoSourceTextAnchor,
	#superclass : #FASTPharoSourceAnchor,
	#traits : 'FamixTWithImmediateSource',
	#classTraits : 'FamixTWithImmediateSource classTrait',
	#category : #'FAST-Pharo-Model-Entities'
}

{ #category : #meta }
FASTPharoSourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FASTPharoSourceAnchor>
	<package: #'FAST-Pharo-Model'>
	<generated>
	^self
]
