Class {
	#name : #FASTPharoExpressionStatement,
	#superclass : #FASTPharoEntity,
	#traits : 'FASTTExpressionStatement',
	#classTraits : 'FASTTExpressionStatement classTrait',
	#category : #'FAST-Pharo-Model-Entities'
}

{ #category : #meta }
FASTPharoExpressionStatement class >> annotation [

	<FMClass: #ExpressionStatement super: #FASTPharoEntity>
	<package: #'FAST-Pharo-Model'>
	<generated>
	^self
]
