Class {
	#name : #FASTPharoSymbolLiteral,
	#superclass : #FASTLiteral,
	#category : #'FAST-Pharo-Model-Entities'
}

{ #category : #meta }
FASTPharoSymbolLiteral class >> annotation [

	<MSEClass: #SymbolLiteral super: #FASTLiteral>
	<package: #'FAST-Pharo-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTPharoSymbolLiteral class >> generatedSlotNames [
	<generated>
	'FASTPharoSymbolLiteral class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTPharoSymbolLiteral class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTPharoSymbolLiteral class >> requirements [

	<generated>
	^ {  }
]
