Class {
	#name : #FASTPharoNumberLiteral,
	#superclass : #FASTLiteral,
	#category : #'FAST-Pharo-Model-Entities'
}

{ #category : #meta }
FASTPharoNumberLiteral class >> annotation [

	<MSEClass: #NumberLiteral super: #FASTLiteral>
	<package: #'FAST-Pharo-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTPharoNumberLiteral class >> generatedSlotNames [
	<generated>
	'FASTPharoNumberLiteral class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTPharoNumberLiteral class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTPharoNumberLiteral class >> requirements [

	<generated>
	^ {  }
]
