Class {
	#name : #FASTPharoSourceTextAnchor,
	#superclass : #FASTPharoSourceAnchor,
	#traits : 'FamixTWithImmediateSource',
	#classTraits : 'FamixTWithImmediateSource classTrait',
	#category : #'FAST-Pharo-Model-Entities'
}

{ #category : #meta }
FASTPharoSourceTextAnchor class >> annotation [

	<MSEClass: #SourceTextAnchor super: #FASTPharoSourceAnchor>
	<package: #'FAST-Pharo-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTPharoSourceTextAnchor class >> generatedSlotNames [
	<generated>
	'FASTPharoSourceTextAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTPharoSourceTextAnchor class >> generatedTraitNames [
	<generated>
	^ #(FamixTWithImmediateSource)
]

{ #category : #meta }
FASTPharoSourceTextAnchor class >> requirements [

	<generated>
	^ {  }
]
