Class {
	#name : #FASTPharoExpression,
	#superclass : #FASTExpression,
	#category : #'FAST-Pharo-Model-Entities'
}

{ #category : #meta }
FASTPharoExpression class >> annotation [

	<MSEClass: #Expression super: #FASTExpression>
	<package: #'FAST-Pharo-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTPharoExpression class >> generatedSlotNames [
	<generated>
	'FASTPharoExpression class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTPharoExpression class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTPharoExpression class >> requirements [

	<generated>
	^ {  }
]
